INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Rufer','Reinstrasse 599','Psychotherapie','test1','1123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Mader','Schlossweg 50','Allgemein Therapie', 'test2','2123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Meyer','Brunnstrasse 39','Schizophrenie','test3','3123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Oesch','Eichweg 29','Esstörung' ,'test4','4123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Trachsel','Bahnhofplatz 1','Affektive Erkrankungen','test5','5123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Klembowski','Bahnstrasse 99','Sucht' ,'test6','6123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Witschi','Sandrainstrasse 99','Forensik','test7','7123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Hofmann','Viktoriastrasse 100','Affektive Erkrankungen','test8','8123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Schüpbach','Wankdorffeldstrasse 12','Affektive Erkrankungen','test9','9123');
INSERT INTO arzt(name, adresse, spezialgebiet, username, password) VALUES ('Tritten','Huberstrasse 10','Affektive Erkrankungen','test0','0123');
