INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Rufer','Reinstrasse 599','psychotherapy','test1','1123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Mader','Schlossweg 50','general therapy', 'test2','2123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Meyer','Brunnstrasse 39','schizophrenia','test3','3123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Oesch','Eichweg 29','eating disorder' ,'test4','4123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Trachsel','Bahnhofplatz 1','affective illness','test5','5123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Klembowski','Bahnstrasse 99','addiction' ,'test6','6123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Witschi','Sandrainstrasse 99','forensic','test7','7123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Hofmann','Viktoriastrasse 100','psychotherapy','test8','8123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Schüpbach','Wankdorffeldstrasse 12','forensic','test9','9123');
INSERT INTO doctor(name, adress, specialisation, username, password) VALUES ('Tritten','Huberstrasse 10','addiction','test0','0123');
